### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Fa113n5tar**

### CODE REVIEW

**Comment by Fa113n5tar** [comment]
Sorry, forgot to add a comment to the commit- this is Tagpro's design file for addition to the script

**Comment by catalyst518** [comment]
This doesn't quite line up with the official TagPro plan. https://docs.google.com/spreadsheets/d/1ugBSrUBKoFE5fYp8J0qSIVxs94W8__z9N5bFhoKDA2Y/edit#gid=247418584

For example, check the spacing between the red ball and the left of the Ukraine colors.

**Comment by Fa113n5tar** [comment]
> This doesn't quite line up with the official TagPro plan. https://docs.google.com/spreadsheets/d/1ugBSrUBKoFE5fYp8J0qSIVxs94W8__z9N5bFhoKDA2Y/edit#gid=247418584
> 
> For example, check the spacing between the red ball and the left of the Ukraine colors.

That's because that was from before there was an accidental expansion left of 2 pixels, which leaves the entire side unaligned. This copy, adjusted by 4x32 on their discord and mapped to an overlay by me, recenters it.

**Comment by Fa113n5tar** [comment]
Edited my fork so it's self sufficient for now, feel free to accept or decline any of these, or push them to a new branch rather than main, like I see XQC has been.

**Comment by Fa113n5tar** [comment]
The tagpro_template now matches what is on the official documentation, while tagpro_template_centered is the file I originally placed here

**Comment by catalyst518** [comment]
Note that the TagPro developers (me and others) are maintaining the official TagPro design here in case this PR becomes out of sync with the design: https://github.com/catalyst518/tagpro_place_template

**Comment by Fa113n5tar** [comment]
I can remove the PR, if you'd prefer- it was initially put through because I wanted to make sure it was around and people have already been sharing this script.

**Comment by Fa113n5tar** [comment]
Removing because of location change

**Pull request closed without merging**
